"""
JARVIS Core — Curated Philosophical & High-Power Quotes
200 quotes focusing on self-growth, wealth, power, discipline, and high-energy mindset,
with natural conversational pre-phrases for when JARVIS is processing requests.
"""

import random

PRE_PHRASES = [
    "While I compute that, here is a thought to keep in mind:",
    "Allow me a moment to process. In the meantime, consider this:",
    "Thinking... Here is a quote to fuel your drive:",
    "Analyzing your request... Keep this perspective in mind:",
    "Running orchestrations... Here is a powerful insight for you:",
    "Working on it... Remember this:",
    "Give me a brief moment. While I work, here is a thought on growth:",
    "Processing your request... Here is an empowering thought:",
]

QUOTES = [
    # Self-Growth & Mastery (1-40)
    "We are what we repeatedly do. Excellence, then, is not an act, but a habit. — Aristotle",
    "He who has a why to live can bear almost any how. — Friedrich Nietzsche",
    "No man has the right to be an amateur in the matter of physical training. It is a shame for a man to grow old without seeing the beauty and strength of which his body is capable. — Socrates",
    "You have power over your mind, not outside events. Realize this, and you will find strength. — Marcus Aurelius",
    "The soul becomes dyed with the color of its thoughts. — Marcus Aurelius",
    "Difficulties strengthen the mind, as labor does the body. — Seneca",
    "First say to yourself what you would be; and then do what you have to do. — Epictetus",
    "It is not death that a man should fear, but he should fear never beginning to live. — Marcus Aurelius",
    "Waste no more time arguing about what a good man should be. Be one. — Marcus Aurelius",
    "If it is not right do not do it; if it is not true do not say it. — Marcus Aurelius",
    "Man conquereth the world by conquering himself. — Zeno of Citium",
    "Discipline equals freedom. — Jocko Willink",
    "The obstacle is the way. — Ryan Holiday",
    "Don't wish it were easier. Wish you were better. — Jim Rohn",
    "The price of excellence is discipline. The cost of mediocrity is disappointment. — William Arthur Ward",
    "Small daily improvements over time lead to stunning results. — Robin Sharma",
    "Do not pray for an easy life, pray for the strength to endure a difficult one. — Bruce Lee",
    "Knowing is not enough, we must apply. Willing is not enough, we must do. — Bruce Lee",
    "The man who moves a mountain begins by carrying away small stones. — Confucius",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
    "Fortune favors the bold. — Virgil",
    "Iron sharpens iron, so one man sharpens another. — Proverbs",
    "To control yourself is true power. — Lao Tzu",
    "What we achieve inwardly will change outer reality. — Plutarch",
    "He is a wise man who does not grieve for the things which he has not, but rejoices for those which he has. — Epictetus",
    "Continuous effort, not strength or intelligence, is the key to unlocking our potential. — Winston Churchill",
    "Action is the foundational key to all success. — Pablo Picasso",
    "Your focus determines your reality. — Qui-Gon Jinn",
    "Fall seven times, stand up eight. — Japanese Proverb",
    "A smooth sea never made a skilled sailor. — Franklin D. Roosevelt",
    "Build your own dreams, or someone else will hire you to build theirs. — Farrah Gray",
    "Great things are done by a series of small things brought together. — Vincent van Gogh",
    "Do what you can, with what you have, where you are. — Theodore Roosevelt",
    "Doubt kills more dreams than failure ever will. — Suzy Kassem",
    "I am not a product of my circumstances. I am a product of my decisions. — Stephen Covey",
    "Energy and persistence conquer all things. — Benjamin Franklin",
    "Character is destiny. — Heraclitus",
    "Without ambition one starts nothing. Without work one finishes nothing. — Ralph Waldo Emerson",
    "Believe you can and you're halfway there. — Theodore Roosevelt",
    "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",

    # Power & Mindset (41-80)
    "To lead people, walk behind them. — Lao Tzu",
    "When you are content to be simply yourself and don't compare or compete, everyone will respect you. — Lao Tzu",
    "Mastering others is strength. Mastering yourself is true power. — Lao Tzu",
    "In the midst of chaos, there is also opportunity. — Sun Tzu",
    "The supreme art of war is to subdue the enemy without fighting. — Sun Tzu",
    "He will win who knows when to fight and when not to fight. — Sun Tzu",
    "Let your plans be dark and impenetrable as night, and when you move, fall like a thunderbolt. — Sun Tzu",
    "Victorious warriors win first and then go to war, while defeated warriors go to war first and then seek to win. — Sun Tzu",
    "He who defends everywhere defends nowhere. — Sun Tzu",
    "Success is most often achieved by those who don't know that failure is inevitable. — Coco Chanel",
    "Never yield to force; never yield to the apparently overwhelming might of the enemy. — Winston Churchill",
    "A leader is one who knows the way, goes the way, and shows the way. — John C. Maxwell",
    "Power is not given, it is taken. — Bernardo Provenzano",
    "Always say less than necessary. — Robert Greene",
    "So much depends on reputation, guard it with your life. — Robert Greene",
    "Court attention at all cost. — Robert Greene",
    "Get others to do the work for you, but always take the credit. — Robert Greene",
    "Make people come to you, use bait if necessary. — Robert Greene",
    "Win through your actions, never through argument. — Robert Greene",
    "Conceal your intentions. — Robert Greene",
    "When you show yourself to the world and display your talents, you naturally stir up envy and resentment. — Robert Greene",
    "Do not leave your reputation to chance or gossip; it is your life's artwork. — Robert Greene",
    "Lord, save me from my friends, I can take care of my enemies. — Voltaire",
    "The greatest warrior is the inspired man. — Sun Tzu",
    "Stand erect, shoulders back. Face the world with strength. — Jordan Peterson",
    "Compare yourself to who you were yesterday, not to who someone else is today. — Jordan Peterson",
    "If you want to be dangerous, master your body and your mind. — Jordan Peterson",
    "The lion doesn't turn around when a small dog barks. — African Proverb",
    "A wolf does not concern himself with the opinions of sheep. — George R.R. Martin",
    "If you want peace, prepare for war. — Vegetius",
    "He who fears suffering already suffers from the fear. — Michel de Montaigne",
    "Courage is grace under pressure. — Ernest Hemingway",
    "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self. — Ernest Hemingway",
    "He who is brave is free. — Seneca",
    "No man is free who is not master of himself. — Epictetus",
    "A conqueror is tested in adversity. — Alexander the Great",
    "There is nothing impossible to him who will try. — Alexander the Great",
    "I am not afraid of an army of lions led by a sheep; I am afraid of an army of sheep led by a lion. — Alexander the Great",
    "He who commands himself commands the world. — Julius Caesar",
    "Veni, vidi, vici. I came, I saw, I conquered. — Julius Caesar",

    # Wealth, Money & Ambition (81-120)
    "Wealth consists not in having great possessions, but in having few wants. — Epictetus",
    "Rule No. 1: Never lose money. Rule No. 2: Never forget rule No. 1. — Warren Buffett",
    "The best investment you can make is an investment in yourself. — Warren Buffett",
    "Price is what you pay. Value is what you get. — Warren Buffett",
    "Someone's sitting in the shade today because someone planted a tree a long time ago. — Warren Buffett",
    "Opportunities come infrequently. When it rains gold, put out the bucket, not the thimble. — Warren Buffett",
    "Formal education will make you a living; self-education will make you a fortune. — Jim Rohn",
    "Money is a terrible master but an excellent servant. — P.T. Barnum",
    "If you don't find a way to make money while you sleep, you will work until you die. — Warren Buffett",
    "Rich people acquire assets. The poor and middle class acquire liabilities that they think are assets. — Robert Kiyosaki",
    "The single most powerful asset we all have is our mind. — Robert Kiyosaki",
    "Don't work for money; make money work for you. — Robert Kiyosaki",
    "Financial freedom is available to those who learn about it and work for it. — Robert Kiyosaki",
    "Focus on building equity, not just earning income. — Naval Ravikant",
    "Seek wealth, not money or status. Wealth is having assets that earn while you sleep. — Naval Ravikant",
    "You're not going to get rich trading your time for money. — Naval Ravikant",
    "Arm yourself with specific knowledge, accountability, and leverage. — Naval Ravikant",
    "Play iterated games. All the returns in life come from compound interest. — Naval Ravikant",
    "Productize yourself. — Naval Ravikant",
    "Learn to build. Learn to sell. If you can do both, you will be unstoppable. — Naval Ravikant",
    "Freedom is the ultimate goal of wealth. — Naval Ravikant",
    "The secret of wealth is simple: find a way to do more for others than anyone else does. — Tony Robbins",
    "If you want to be wealthy, think long term. — Naval Ravikant",
    "Wealth is the ability to fully experience life. — Henry David Thoreau",
    "It's not how much money you make, but how much money you keep. — Robert Kiyosaki",
    "Money grows on the tree of persistence. — Japanese Proverb",
    "The goal isn't more money. The goal is living life on your terms. — Chris Brogan",
    "Wealth is not about having a lot of money; it's about having a lot of options. — Chris Rock",
    "Money is power, and you ought to be reasonably ambitious to have it. — Russell Conwell",
    "Every dollar is a vote for the future you want to create. — E.F. Schumacher",
    "A wise man should have money in his head, but not in his heart. — Jonathan Swift",
    "Capitalism is about turning capital into freedom. — Naval Ravikant",
    "Work hard in silence, let your success be your noise. — Frank Ocean",
    "Opportunities don't happen. You create them. — Chris Grosser",
    "Do not save what is left after spending, but spend what is left after saving. — Warren Buffett",
    "Never depend on single income. Make investment to create a second source. — Warren Buffett",
    "Wealth flows to those who add value. — Brian Tracy",
    "If you want to double your income, double your rate of learning. — Brian Tracy",
    "Ambition is the path to success. Persistence is the vehicle you arrive in. — Bill Bradley",
    "The key to wealth is execution over ideas. — Felix Dennis",

    # Drive, Strength & Testosterone Boosters (121-160)
    "Pain is temporary. It may last a minute, or an hour, or a day, or a year, but eventually it will subside. — Eric Thomas",
    "When you want to succeed as bad as you want to breathe, then you'll be successful. — Eric Thomas",
    "Don't count the days, make the days count. — Muhammad Ali",
    "I hated every minute of training, but I said, don't quit. Suffer now and live the rest of your life as a champion. — Muhammad Ali",
    "The fight is won or lost far away from witnesses, in the gym and out there on the road. — Muhammad Ali",
    "Silence is a source of great strength. — Lao Tzu",
    "The harder the conflict, the more glorious the triumph. — Thomas Paine",
    "Strength does not come from winning. Your struggles develop your strengths. — Arnold Schwarzenegger",
    "The resistance that you fight physically in the gym and the resistance that you fight in life can only build a strong character. — Arnold Schwarzenegger",
    "What is the point of being on this Earth if you are going to be like everyone else? — Arnold Schwarzenegger",
    "You have to remember that you can't be afraid of failing. — Arnold Schwarzenegger",
    "Obsessed is just a word the lazy use to describe the dedicated. — Unknown",
    "Be relentless in the pursuit of what sets your soul on fire. — Unknown",
    "Stay hungry, stay foolish. — Steve Jobs",
    "The people who are crazy enough to think they can change the world are the ones who do. — Steve Jobs",
    "Work like there is someone working 24 hours a day to take it away from you. — Mark Cuban",
    "If you're going through hell, keep going. — Winston Churchill",
    "Never, never, never give up. — Winston Churchill",
    "It always seems impossible until it's done. — Nelson Mandela",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
    "Mastery demands sacrifice. — Unknown",
    "Run when you can, walk if you have to, crawl if you must; just never give up. — Dean Karnazes",
    "Soft execution produces soft results. Demand intensity. — Unknown",
    "Limitless is a state of mind. — Unknown",
    "Clear your mind of can't. — Samuel Johnson",
    "Don't stop when you're tired. Stop when you're done. — David Goggins",
    "You are in danger of living a life so comfortable that you will die without realizing your true potential. — David Goggins",
    "Suffering is the true test of life. — David Goggins",
    "We don't rise to the level of our expectations, we fall to the level of our training. — Archilochus",
    "The pain you feel today will be the strength you feel tomorrow. — Unknown",
    "Be the hammer, not the anvil. — Erle Stanley Gardner",
    "Greatness is forged in fire. — Unknown",
    "Hard work beats talent when talent fails to work hard. — Tim Notke",
    "Rise and grind. The world waits for no one. — Unknown",
    "Build a mind that is unshakeable. — Unknown",
    "Dominance is earned, not given. — Unknown",
    "Execute relentlessly. — Unknown",
    "Your output defines your caliber. — Unknown",
    "Focus on the work, the results will follow. — Unknown",
    "Keep your eyes on the prize and your feet on the gas. — Unknown",

    # Unstoppable Execution & Vision (161-200)
    "Vision without execution is hallucination. — Thomas Edison",
    "Genius is one percent inspiration and ninety-nine percent perspiration. — Thomas Edison",
    "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
    "The secret of getting ahead is getting started. — Mark Twain",
    "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. — Mark Twain",
    "He who moves first controls the battlefield. — Miyamoto Musashi",
    "Think lightly of yourself and deeply of the world. — Miyamoto Musashi",
    "Do nothing that is of no use. — Miyamoto Musashi",
    "There is nothing outside of yourself that can ever enable you to get better. Everything is within. — Miyamoto Musashi",
    "In strategy it is important to see distant things as if they were close and to take a distanced view of close things. — Miyamoto Musashi",
    "Perception is strong and sight weak. — Miyamoto Musashi",
    "Fix your eyes on the target and let nothing distract your trajectory. — Unknown",
    "A winner is a dreamer who never gives up. — Nelson Mandela",
    "Speed of execution is the ultimate competitive advantage. — Unknown",
    "Do it with passion or not at all. — Rosa Nouchette Carey",
    "Success is the sum of small efforts, repeated day in and day out. — Robert Collier",
    "Courage is not the absence of fear, but the triumph over it. — Nelson Mandela",
    "He who has conquered his own fears is truly free. — Aristotle",
    "Small minds discuss people. Average minds discuss events. Great minds discuss ideas. — Eleanor Roosevelt",
    "Believe in the power of relentless effort. — Unknown",
    "The standard is excellence. Accept nothing less. — Unknown",
    "Conquer from within. — Unknown",
    "Build an empire of execution. — Unknown",
    "Your potential is bounded only by your willingness to act. — Unknown",
    "Tough times never last, but tough people do. — Robert H. Schuller",
    "Turn your wounds into wisdom. — Oprah Winfrey",
    "Discipline is choosing between what you want now and what you want most. — Abraham Lincoln",
    "The best way to predict your future is to create it. — Abraham Lincoln",
    "Give me six hours to chop down a tree and I will spend the first four sharpening the axe. — Abraham Lincoln",
    "Whatever you are, be a good one. — Abraham Lincoln",
    "Patience, persistence and perspiration make an unbeatable combination for success. — Napoleon Hill",
    "The starting point of all achievement is desire. — Napoleon Hill",
    "Whatever the mind can conceive and believe, it can achieve. — Napoleon Hill",
    "A goal is a dream with a deadline. — Napoleon Hill",
    "Great minds have purposes, others have wishes. — Washington Irving",
    "Self-mastery is the ultimate victory. — Unknown",
    "Focus like a laser, execute like a machine. — Unknown",
    "Rule your day, rule your destiny. — Unknown",
    "Unstoppable mindset. Flawless execution. — Unknown",
    "Project JARVIS online. Power, focus, and drive engaged. — JARVIS",
]


def get_random_quote() -> str:
    """Returns a random inspiring philosophical/power quote."""
    return random.choice(QUOTES)


def get_thinking_phrase() -> str:
    """Returns a natural transition phrase followed by a random quote."""
    phrase = random.choice(PRE_PHRASES)
    quote = get_random_quote()
    return f"{phrase} {quote}"


def get_greeting_quote() -> str:
    """Returns the personalized greeting and inspirational quote on wake word trigger."""
    quote = get_random_quote()
    return f"Hi Kamal, how are you today? Here is an idea for today: {quote}"

